INSERT INTO STOCK_PRICE(PRICE_ID,COMPANY_NAME,STOCK_COST) VALUES(101, 'BHEL', 36.40);
INSERT INTO STOCK_PRICE(PRICE_ID,COMPANY_NAME,STOCK_COST) VALUES(102, 'SBI', 273.50);
INSERT INTO STOCK_PRICE(PRICE_ID,COMPANY_NAME,STOCK_COST) VALUES(103, 'GAIL', 122.45);
INSERT INTO STOCK_PRICE(PRICE_ID,COMPANY_NAME,STOCK_COST) VALUES(104, 'TCS', 2835.00);